accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>/', views.detail, name='detail'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:pk>/like/', views.like, name='like'),
]

django_form/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from articles import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import hashlib
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(
            settings.AUTH_USER_MODEL,
            related_name='followings'
        )

    @property
    def gravatar_url(self):
        return f"https://s.gravatar.com/avatar/{hashlib.md5(self.email.encode('utf-8').strip().lower()).hexdigest()}?s=80"

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill, ResizeToFit, Thumbnail
# ResizeToFill : 300*300 자르는 것(crop)
# ResizeToFit : 가장 긴 곳(너비/높이)을 300으로 맞추고, 비율에 맞춰서

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # 원본 저장 + 자른 것을 활용 : ImageSpecField + source
    image = models.ImageField()
    # DB 저장 X, 호출하게되면, 잘라서 표현
    image_thumbnail = ImageSpecField(source='image',
                          processors=[Thumbnail(300, 300)],
                          format='JPEG',
                          options={'quality': 60})
    # 원본 잘라서 저장 : ProcessedImageField
    # image = ProcessedImageField(
    #                       processors=[ResizeToFill(100, 50)],
    #                       format='JPEG',
    #                       options={'quality': 60})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    # articles_article_like_users 테이블 생성
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='like_articles')

class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article,
                                on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

accounts/forms.py
# from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

# 그대로 활용하지 못하는 경우는 항상 상속받아서 custom!!!!
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email']

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.http import require_POST

from .forms import CustomUserChangeForm, CustomUserCreationForm

# Create your views here.
def signup(request):
    # 로그인이 되어있다면,
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # 게시글 목록 페이지
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

def detail(request, pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=pk)
    context = {
        'user': user
    }
    return render(request, 'accounts/detail.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        # 사용자가 보낸 값 -> form
        form = AuthenticationForm(request, request.POST)
        # 검증
        if form.is_valid():
            # 검증 완료시 로그인!
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    # 조건식으로 직접 작성 해도 된다.
    auth_logout(request)
    return redirect('articles:index')

@require_POST
@login_required
def delete(request):
    request.user.delete()
    return redirect('articles:index')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

def follow(request, pk):
    User = get_user_model()
    # 팔로우 당하는 사람
    user = get_object_or_404(User, pk=pk)
    if user != request.user:
        # 팔로우를 요청한 사람 => request.user
        # 팔로우가 되어 있다면,
        if user.followers.filter(pk=request.user.pk).exists():
            # 삭제
            user.followers.remove(request.user)
        else:
            # 추가
            user.followers.add(request.user)
    return redirect('accounts:detail', user.pk)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}
<h1>{{ user.pk }} : {{ user.username }}</h1>
{% with user_followers=user.followers.all %}
    {% if request.user == user %}
        <a href="{% url 'accounts:update' %}">회원 수정</a>
        <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-secondary">회원 탈퇴</button>
        </form>
    {% else %}
        <hr>
            {% if request.user in user_followers %}
                <a href="{% url 'accounts:follow' user.pk %}">팔로우 취소</a>
            {% else %}
                <a href="{% url 'accounts:follow' user.pk %}">팔로우</a>
            {% endif %}
    {% endif %}
    <p> {{ user_followers|length }}명이 팔로우하고 있습니다.</p>
    <p> {{ user.followings.count }}명을 내가 팔로우하고 있습니다.</p>
{% endwith %}
<hr>
<h3>작성한 글 목록</h3>
{% for article in user.article_set.all %}
    <a href="{% url 'articles:detail' article.pk %}">
        <p>{{ article.title }}</p>
    </a>
{% endfor %}
<h3>좋아요한 글 목록</h3>
{% for article in user.like_articles.all %}
    <a href="{% url 'articles:detail' article.pk %}">
        <p>{{ article.title }}</p>
    </a>
{% endfor %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block body %}
    <h2 class="text-center">로그인</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary">로그인</button>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block body %}
    <h2 class="text-center">회원가입</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary">회원가입 신청</button>
        <a href="{% url 'accounts:login' %}">로그인</a>
    </form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary">수정</button>
    </form>
{% endblock %}