accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>/', views.detail, name='detail'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:pk>/like/', views.like, name='like'),
]

django_form/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from articles import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill, ResizeToFit, Thumbnail
# ResizeToFill : 300*300 자르는 것(crop)
# ResizeToFit : 가장 긴 곳(너비/높이)을 300으로 맞추고, 비율에 맞춰서

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # 원본 저장 + 자른 것을 활용 : ImageSpecField + source
    image = models.ImageField()
    # DB 저장 X, 호출하게되면, 잘라서 표현
    image_thumbnail = ImageSpecField(source='image',
                          processors=[Thumbnail(300, 300)],
                          format='JPEG',
                          options={'quality': 60})
    # 원본 잘라서 저장 : ProcessedImageField
    # image = ProcessedImageField(
    #                       processors=[ResizeToFill(100, 50)],
    #                       format='JPEG',
    #                       options={'quality': 60})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    # articles_article_like_users 테이블 생성
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='like_articles')

class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article,
                                on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'image']

class CommentForm(forms.ModelForm):
    content = forms.CharField(
                label='댓글',
                widget=forms.Textarea(
                        attrs={
                            'rows': 2,
                        }
                    )
            )
    class Meta:
        model = Comment
        fields = ['content']

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponseForbidden, HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Article
from .forms import ArticleForm, CommentForm
# Create your views here.
def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'articles/form.html', context)

def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    form = CommentForm()
    context = {
        'article': article,
        'form': form
    }
    return render(request, 'articles/detail.html', context)

@require_POST
@login_required
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user == article.user:
        article.delete()
    return redirect('articles:index')

@login_required
def update(request, pk):
    # 수정시에는 해당 article 인스턴스를 넘겨줘야한다!
    article = get_object_or_404(Article, pk=pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                article = form.save(commit=False)
                article.user = request.user
                article.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
        context = {
            'form': form
        }
        return render(request, 'articles/form.html', context)
    else:
        # 1. 메시지프레임워크를 사용하여, 메인페이지로 이동.
        messages.warning(request, '본인 글만 수정 가능합니다.')
        return redirect('articles:index')
        # 2. 403 status code를 반환.
        # return HttpResponseForbidden()

# @login_required
@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.article = article
            comment.save()
        return redirect('articles:detail', article.pk)
    else:
        # 1. next parameter 없이 진행.
        messages.warning(request, '댓글 작성을 위해서는 로그인이 필요합니다.')
        return redirect('accounts:login')
        # return HttpResponse(status=401)

def like(request, pk):
    article = get_object_or_404(Article, pk=pk)
    # request.user
    # 좋아요를 누른적이 있다면, => DB에 저장되어 있으면
    # if request.user in article.like_users.all():
    if article.like_users.filter(id=request.user.pk).exists():
        # 취소
        article.like_users.remove(request.user)
    # 그게 아니면,
    else:
        # 좋아요
        article.like_users.add(request.user)
    return redirect('articles:detail', article.pk)

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block body %}
    <h2>새 글쓰기</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="제출">
    </form>
{% endblock %}

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <h1>{{ article.pk }} : {{ article.title }}</h1>
    <p>{{ article.user.username }}님</p>
    <p class="text-secondary">{{ article.created_at }} | 수정: {{ article.updated_at }}</p>
    {% if article.user == request.user  %}
    <div class="text-right">
        <form action="{% url 'articles:delete' article.pk %}" method="POST" class="d-inline">
            {% csrf_token %}
            <button class="btn btn-secondary">삭제</button>
        </form>
        <a href="{% url 'articles:update' article.pk %}"><button class="btn btn-secondary">수정</button></a>
    </div>
    {% endif %}
    {% with article_like_users=article.like_users.all %}
        {% if request.user in article_like_users %}
        <a href="{% url 'articles:like' article.pk %}">
            <i class="fas fa-heart fa-lg animated delay-1s" style="color: red;"></i>
        </a>
        {% else %}
        <a href="{% url 'articles:like' article.pk %}">
            <i class="far fa-heart fa-lg animated infinite bounce delay-1s" style="color: gray;"></i>
        </a>
        {% endif %}
        <p>{{ article_like_users|length }}명이 좋아합니다.</p>
    {% endwith %}
    <hr>
    <p>{{ article.content }}</p>
    <img src="{{ article.image.url }}">
    <img src="{{ article.image_thumbnail.url }}">
    <hr>
    {% for comment in article.comment_set.all %}
        <li>{{ comment.user.username }} : {{ comment.content }}</li>
    {% endfor %}
    <hr>
    <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary">작성</button>
    </form>

{% endblock %}

articles/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!--
        분기의 기준은 url_name이다.
        path로 하면, url이 바뀔 때마다 바꿔줘야한다.
    -->
    {% if request.resolver_match.url_name == 'create' %}
        <h2>새 글쓰기</h2>
    {% else %}
        <h2>수정하기</h2>
    {% endif %}

    <!-- bootstrap4 활용 -->
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <!-- input type:submit -->
        <button class="btn btn-primary">제출</button>
    </form>
    <hr>
{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% block body %}
    <h2 class="text-center">게시판 목록</h2>
    <a href="{% url 'articles:create' %}"><button class="btn btn-primary float-right my-2">글 쓰기</button></a>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">제목</th>
          <th scope="col">작성자</th>
          <th scope="col">작성 시간</th>
        </tr>
      </thead>
      <tbody>
       {% for article in articles %}
        <tr>
          <th scope="row">{{ article.pk }}</th>
          <td><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></td>
          <td><a href="{% url 'accounts:detail' article.user.pk %}">{{ article.user.username }}</a></td>
          <td>{{ article.created_at }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}

articles/templates/articles/new.html
{% extends 'base.html' %}

{% block body %}
    <h2>새 글쓰기</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="제출">
    </form>
{% endblock %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="수정">
    </form>
{% endblock %}